### ISSUE TITLE
Port to kf5 and qt5

### ISSUE THREAD

**Issue by roberth1990** [dfaust/soundkonverter#23]
Can this application be ported to kde frameworks 5 and qt5?

**Comment by HessiJames** [comment]
There is a branch named qt5 where I started porting and partially rewriting soundkonverter but I don't have the time at the moment to finish it.
There is also a pull request (https://github.com/HessiJames/soundkonverter/pull/22) where some parts are ported to frameworks 5.

**Comment by david-geiger** [comment]
Hi,
Any news about KF5/Qt5 port?

kde4 is now a bit unmaintained upstream.

**Comment by HessiJames** [comment]
I won't write a KF5/Qt5 port, sorry.

**Comment by darkbasic** [comment]
That's sad because it means it's going to die within a year :(
https://marc.info/?l=kde-release-team&m=147881782701604&w=2

**Comment by gericom-hummer** [comment]
Any news about it?
Can you collaborate with [https://github.com/isoft-linux/soundkonverter/](url) so it can be ported for qt5?

And just one silly question. What happened to Hessi James? He gave up on this project and gave to you or?

**Comment by dfaust** [comment]
Nothing has changed, I'm not interested in continuing to write a port. Unfortunately the version at https://github.com/isoft-linux/soundkonverter/ is incomplete, so I can't just merge it.

@gericom-hummer: HessiJames was my previous user name.

**Comment by gericom-hummer** [comment]
I get it? Then let's hope somebody will port it to qt5, as in few months it won't be able to run the app. If these guys started porting it, can you help them complete it. Because if i compile it under arch linux/ kaos / manjaro, it is working very well.

**Comment by dfaust** [comment]
If someone wanted to know something about the code I wrote, I would explain it, no problem. But I just can't get myself to work on it right now. The last thing I tried was getting the plugins to load again. But I couldn't find any documentation of what changed. And that's just frustrating.

And btw. as much as I hate the almost non-existing integration of qt4 apps into a qt5 environment, it's still usable. So why do you think you won't be able to use the qt4 version anymore? Will your distribution remove the qt4 libs?

**Comment by gericom-hummer** [comment]
Not only, i think kde will drop the support for qt4, like they did for qt3 time ago. For sure Arch will bi one of the 1st propping support for qt4, then KaOS, and Manjaro. Debian based will be last. It is working perfectly now. lets hope it will continue.

**Comment by darkbasic** [comment]
They will probably drop everything qt4 related on December 2017, with the new kde-applications.

**Comment by ShalokShalom** [comment]
@gericom-hummer KaOS dropped qt4 already one year ago, its still in Arch repos. 

I think this here can be closed?

**Comment by neoclust** [comment]
is it planned to merge qt5 branch in master ?

**Comment by dfaust** [comment]
@ShalokShalom: The biggest issue is plugin loading, I'm using opensuse and it doesn't work for me. I think there are some more issues, but I haven't looked at it in a while.

**Comment by ShalokShalom** [comment]
Which plugins?

**Comment by dfaust** [comment]
All of them. I think they get installed to the wrong place, but as I said, I haven't looked at it in a while.

**Comment by ShalokShalom** [comment]
Guess it is/was a packaging issue, works here since two years, as stated. :+1:

**Comment by Tids** [comment]
Yep works for me too (using the [AUR pkgbuild](https://aur.archlinux.org/packages/soundkonverter-frameworks-git/)). Only when compiling there are lots and lots of "KUrl;KDialog is deprecated and you should use QUrl/QDialog instead"-warnings. But it runs and converts things.

So for me, thats enough for a v2.95 (3.0 Beta) release :b

**Comment by varlesh** [comment]
Soon devs remove all Qt-4 apps from KDE :(
http://www.phoronix.com/scan.php?page=news_item&px=KDE-Applications-17.08
https://kdepepo.wordpress.com/2017/07/14/kf5-applications-porting

**Comment by r41d** [comment]
Gentoo's package system today told me:
```
# Andreas Sturmlechner <asturm@gentoo.org> (27 Aug 2017)
# Requires deprecated libkcddb:4, upstream is not going to port.
# See also: https://github.com/dfaust/soundkonverter/issues/23
# Masked for removal in 30 days.
```

**Comment by r41d** [comment]
Gentoo's package system today told me:
```
# Andreas Sturmlechner <asturm@gentoo.org> (27 Aug 2017)
# Requires deprecated libkcddb:4, upstream is not going to port.
# See also: https://github.com/dfaust/soundkonverter/issues/23
# Masked for removal in 30 days.
```
So they are dropping support for it, i.e. removing the package... I liked SoundKonverter :(

**Comment by hartwork** [comment]
I like(d) SoundKonverter too. @dfaust, can you make a list of (sub)tasks/obstacles that someone or a team would need to go through to fully migrate to Qt5?

**Comment by ShalokShalom** [comment]
It IS already fully ported to Qt5.

**Comment by dfaust** [comment]
@hartwork I don't have such a list in my head, I will have to take a look.

**Comment by dfaust** [comment]
@ShalokShalom Which soundkonverter version have you tested?

**Comment by ShalokShalom** [comment]
As said, hundreds, maybe thousands of users in KaOS test it since Feb 15.

**Comment by varlesh** [comment]
Changed only `sed -i -e 's|add_custom_target|#add_custom_target|' ${srcdir}/${pkgname}/src/CMakeLists.txt` and cmake prefix

**Comment by ShalokShalom** [comment]
Can you say us something about libkcddb? What do you know about its deprecation?

**Comment by dfaust** [comment]
@ShalokShalom kcddb seems to be maintained and part of KDE Applications (https://phabricator.kde.org/source/libkcddb/)

**Comment by a17r** [comment]
@ShalokShalom libkcddb:4 (as in kdelibs-4 based) is deprecated, of course libkcddb:5 (kf5-based) exists in KDE Applications and is maintained.

**Comment by rikmills** [comment]
Gentoo are referring to the depreciation of the KDE4/Qt4 slot4 version of libkcddb, since this library was ported to KF5/Qt5 for the 16.12 release of KDE applications. Therefore applications that wish to use a supported version of the library from now on need to port to KF5 as well. So most distributions will replace or remove the old versions.

**Comment by ShalokShalom** [comment]
yeah, yeah, i already got it, overlooked that 4 before, thanks a lot

**Comment by hartwork** [comment]
I made a quick ebuild for d153c0d06be68e129cb79d0db4329058e57cfe68: It compiles... but most images in the GUI are missing, may be the packaging or may not. I cannot easily proceed myself from here, but maybe that ebuild I made helps someone else:
[soundkonverter-2.2.2_p20170829.ebuild.txt](https://github.com/dfaust/soundkonverter/files/1261396/soundkonverter-2.2.2_p20170829.ebuild.txt)

@a17r Now that there is ongoing progress, could you drop or at adjust the `removal in 30 days` marker in `profiles/package.mask` for now, please?

**Comment by ShalokShalom** [comment]
![screenshot_20170829_212114](https://user-images.githubusercontent.com/6344099/29839819-0404a676-8d00-11e7-967d-017dfe3b889d.png)

![screenshot_20170829_212147](https://user-images.githubusercontent.com/6344099/29839829-140df3ce-8d00-11e7-8541-143236a266d7.png)

**Comment by IsaacJT** [comment]
I modified @hartwork's ebuild slightly, and it builds fine without any issues or missing icons:

````
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

KDE_LINGUAS="ca cs de es es_AR et fr hu it nl pl pt pt_BR ro ru sl sv zh_CN zh_TW"
inherit kde5

MY_COMMIT=d153c0d06be68e129cb79d0db4329058e57cfe68
DESCRIPTION="Frontend to various audio converters"
HOMEPAGE="http://www.kde-apps.org/content/show.php/soundKonverter?content=29024"
SRC_URI="https://github.com/dfaust/soundkonverter/archive/${MY_COMMIT}.tar.gz -> ${P}.tar.gz"
LICENSE="GPL-2"
SLOT="5"
KEYWORDS="~amd64 ~x86"
IUSE="debug"

RDEPEND="
        media-libs/phonon[qt5]
        >=media-libs/taglib-1.10
        media-sound/cdparanoia
"
DEPEND="${RDEPEND}
        sys-devel/gettext
        $(add_frameworks_dep kconfig)
        $(add_frameworks_dep kconfigwidgets)
        $(add_frameworks_dep kdelibs4support)
        $(add_frameworks_dep ki18n)
        $(add_frameworks_dep kio)
        $(add_frameworks_dep kwidgetsaddons)
        $(add_frameworks_dep kxmlgui)
        $(add_frameworks_dep solid)
        $(add_kdeapps_dep libkcddb)
        $(add_qt_dep qtcore)
        $(add_qt_dep qtnetwork)
        $(add_qt_dep qtwidgets)
"

S="${WORKDIR}"/${PN}-${MY_COMMIT}/src

pkg_postinst() {
        kde5_pkg_postinst

        elog "soundKonverter optionally supports many different audio formats."
        elog "You will need to install the appropriate encoding packages for the"
        elog "formats you require. For a full listing, consult the README file"
        elog "in /usr/share/doc/${PF}"
}
````

**Comment by hartwork** [comment]
@dfaust what is still missing on the road to a tagged new KDE 5 release from your point of view now?

I'm unsure how on- or off-topic commenting on the ebuild is. (Issues I see are that python is still missing and the KDE and Qt libs are linked against (I checked) so they should not be missing from RDEPEND. Also, I see more direct dependencies linked against that we seem missing, see `lddtree /usr/bin/soundkonverter | grep -E '^ {4}[^ ]' | awk '{print $3}' | sort -u | xargs qfile | sort` output.)

**Comment by dfaust** [comment]
@hartwork I would like to import old configurations and profiles and the tag editing doesn't seem to work.

Beside that my cd drive isn't working, so I can't test that. It would be great if someone could see if cd ripping still works.

I think I'll do the import of old configurations and profiles part and leave the rest for the future because releasing a new version is clearly a priority.

**Comment by a17r** [comment]
@hartwork packaging is not the problem, but creating a snapshot is only a very last resort and not something we do casually.

**Comment by hartwork** [comment]
> creating a snapshot is only a very last resort and not something we do casually.

@a17r Yes. So I guess what we would want from a Gentoo (or any Linux distro) perspective is to see that the project is alive, has kf5 code merged to master and a release tag to package, right?

**Comment by hartwork** [comment]
> Beside that my cd drive isn't working, so I can't test that. It would be great if someone could see if cd ripping still works.

@dfaust I just ripped a few tracks off a CD fine. For the future, if sponsoring an external CD drive for you would help, please contact me via e-mail; please mention if you have a PATA-to-USB bridge around or if that would be among the acceptable setups.

To ease testing on Gentoo a bit, I have put an [extended version of @IsaacJT's ebuild](https://cgit.gentoo.org/proj/betagarden.git/tree/media-sound/soundkonverter) into the [betagarden overlay](https://cgit.gentoo.org/proj/betagarden.git/) now:
```
sudo layman -a betagarden
sudo emerge -av =media-sound/soundkonverter-2.2.2_p20170829-r2
```

**Comment by dfaust** [comment]
@hartwork Thank you for testing, but a CD drive won't be necessary, I have one. It isn't working right now (I blame opensuse tumbleweed) but I don't have the time to find out why, another drive probably won't help.

**Comment by dfaust** [comment]
Hooray! I finally tagged soundkonverter 3.0.0. It's not perfect and not well tested, but I simply don't have the time to do it and I wanted to bring this drama to a close. If you find any bugs, please report them and I will fix them if I find the time.

Thanks to everybody who helped with this release, especially @valeth for doing most of the KF5 port and @xiangzhai for porting libkcddb.

**Comment by darkbasic** [comment]
Great, it would have been a pity if it died.

**Comment by ShalokShalom** [comment]
nice timing: https://lists.debian.org/debian-devel-announce/2017/08/msg00006.html

**Comment by valeth** [comment]
I updated the AUR package to use this repo again and removed the `kdelibs4support` dependency.
It built for me, but I didn't try building it in a clean environment.

**Comment by a17r** [comment]
@valeth: soundkonverter still depends on `KF5KDELibs4Support` unless you patched it out of `CMakeLists.txt`. It is not to be confused with `kdelibs4`.

**Comment by valeth** [comment]
Ah, yeah it's still there.
I thought @dfaust removed the dependency to `kdelibs4support`.
Added it again.

**Comment by ZedPea** [comment]
Just tried out the new version, it seems to work fine on single files, but when I use the add folder option, and on the directory output use "Source directory", the output filename is simply /extension, for example in my case the output filename is "/ogg". 

If you try to run regardless, I get a lot of errors about malformed urls.

The output of one of these errors can be seen here: https://pastebin.com/aEpienwD

And the attached picture shows the conversion options I'm using.

![picture](https://user-images.githubusercontent.com/22151537/30464429-01614384-99c1-11e7-8e43-5da83d1241c3.jpg)

I'm not sure if it's something to do with the files not being escaped properly, as that is indeed the correct filepath for the file as long as it's quoted.

If I just use add file, and still use the source directory as the output directory, it converts just fine with the same file.

I'm using the latest version from the arch repos. 
I reinstalled, and deleted any config files I could find in case they were interfering, but I don't think I got all of them as some of my settings seem to have remained.

**Comment by ShalokShalom** [comment]
I can reproduce this issue in a different manner. 
When I set everything as ZedPea does, appears an empty list here:

![screenshot_20170915_085509](https://user-images.githubusercontent.com/6344099/30470073-9839fa30-99f3-11e7-85e4-1d0aa186854b.png)

This are the settings:

![screenshot_20170915_085232](https://user-images.githubusercontent.com/6344099/30470153-e355d7c8-99f3-11e7-8d01-418cee02d250.png)

I use the current 3.0.0 release on Qt 5.9.1

Here is the log from this session:

```
➜  ~ soundkonverter        
kf5.kcoreaddons.kaboutdata: Could not initialize the equivalent properties of Q*Application: no instance (yet) existing.
➜  ~ kf5.kcoreaddons.kaboutdata: QCoreApplication::applicationVersion "" is out-of-sync with KAboutData::applicationData().version "2.2.2"
kf5.kcoreaddons.kaboutdata: QGuiApplication::applicationDisplayName "soundkonverter" is out-of-sync with KAboutData::applicationData().displayName "soundKonverter"
kf5.kcoreaddons.kaboutdata: QGuiApplication::desktopFileName "" is out-of-sync with KAboutData::applicationData().desktopFileName "org.kde.soundkonverter"
kf5.kio.core: We got some errors while running testparm "Load smb config files from /etc/samba/smb.conf\nError loading services.\n"
kf5.kio.core: KSambaShare: Could not find smb.conf!
kf5.kio.core: We got some errors while running 'net usershare info'
kf5.kio.core: "Can't load /etc/samba/smb.conf - run testparm to debug it\n"
QXcbConnection: XCB error: 3 (BadWindow), sequence: 3444, resource id: 34630017, major code: 40 (TranslateCoords), minor code: 0
QObject::connect: No such signal DirOpener::open(const KUrl&,bool,const QStringList&,ConversionOptions*)
QObject::disconnect: No such signal DirOpener::open(const KUrl&,bool,const QStringList&,ConversionOptions*)
QObject::connect: No such signal DirOpener::open(const KUrl&,bool,const QStringList&,ConversionOptions*)
QObject::disconnect: No such signal DirOpener::open(const KUrl&,bool,const QStringList&,ConversionOptions*)

```

**Comment by dfaust** [comment]
@ZedPea Thanks, I had a quick look at it but couldn't find the issue, but I'm on it.

@ShalokShalom Are you sure you are running the latest version? The std output shows version "2.2.2". Also in your case the DirOpener::open signal can't be connected, so that's a different issue.

I moved the issue to #57.

**Comment by ShalokShalom** [comment]
Correct, I did the mistake to look, which version the distribution use, so I was left behind with the updates. 
Its solved in 3.0.0, thanks for making me aware about that. Great +1

**Comment by wopawi** [comment]
hai dfaust,
sorry, but here the < Failed > problem still exists in soundkonverter 3.0.0  installed in antergos/kde

no conversion from mp3-folders to source dir . specified dir . copy dir structure
only single files to source-directory works

looks like description  in < https://github.com/dfaust/soundkonverter/issues/58 >
any idea how to solve?
